repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: ^backend/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        files: ^backend/.*\.py$
        args: [--fix, --exit-non-zero-on-fix]

  # JavaScript/TypeScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md)$

  # ESLint for JavaScript/TypeScript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/parser@6.15.0'
          - '@typescript-eslint/eslint-plugin@6.15.0'

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^frontend/package-lock\.json$
      - id: check-merge-conflict
      - id: detect-private-key
      
  # Custom secret detection
  - repo: local
    hooks:
      - id: detect-secrets
        name: Detect secrets and API keys
        entry: python .pre-commit-hooks/detect-secrets.py
        language: system
        pass_filenames: false
      
      # Fast unit tests (subset)
      - id: unit-tests-fast
        name: Run fast unit tests
        entry: python -m pytest tests/unit/test_ingest_subprocess.py tests/unit/test_ingest_config.py -m unit -q
        language: system
        pass_filenames: false
        stages: [commit]
