services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: askdrchaffee-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-askdrchaffee}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: askdrchaffee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: askdrchaffee-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/askdrchaffee
      - REDIS_URL=redis://redis:6379/0
      - YT_DLP_PATH=yt-dlp
      - FFMPEG_PATH=ffmpeg
      - WHISPER_CACHE_DIR=/tmp/whisper_cache
      - TEMP_AUDIO_DIR=/tmp/audio_downloads
    volumes:
      - whisper_cache:/tmp/whisper_cache
      - audio_temp:/tmp/audio_downloads
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  whisper_cache:
    driver: local
  audio_temp:
    driver: local
