name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov
      
      - name: Run unit tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:${PWD}/backend"
          pytest tests/unit/ -v --tb=short
        env:
          DATABASE_URL: postgresql://test:test@localhost/test
      
      - name: Run linting
        run: |
          pip install ruff black
          ruff check backend/
          black --check backend/
        continue-on-error: true
  
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        run: railway up --service backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Notify deployment
        if: success()
        run: |
          echo "✅ Backend deployed successfully!"
          echo "URL: https://api.askdrchaffee.com"
