name: Nightly Full Test Suite

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  full-test-suite:
    name: Full Test Suite
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      - name: Run all unit tests
        run: |
          pytest tests/unit/ -v --tb=short --durations=20
        env:
          PYTHONPATH: ${{ github.workspace }};${{ github.workspace }}/backend
      
      - name: Run integration tests (if any)
        continue-on-error: true
        run: |
          pytest tests/integration/ -v --tb=short
        env:
          PYTHONPATH: ${{ github.workspace }};${{ github.workspace }}/backend
      
      - name: Generate coverage report
        run: |
          pytest tests/unit/test_ingest_*.py -m unit --cov=backend/scripts --cov-branch --cov-report=html --cov-report=term
        env:
          PYTHONPATH: ${{ github.workspace }};${{ github.workspace }}/backend
      
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30
      
      - name: Performance benchmarks
        run: |
          echo "## Performance Benchmarks" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          pytest tests/unit/test_ingest_*.py -m unit --durations=0 >> $GITHUB_STEP_SUMMARY
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Nightly test suite failed" >> $GITHUB_STEP_SUMMARY
          echo "Check the logs for details" >> $GITHUB_STEP_SUMMARY

  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install pip-audit
      
      - name: Audit dependencies
        run: |
          pip-audit --desc --format json > audit-report.json || true
          pip-audit --desc
      
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-audit
          path: audit-report.json
          retention-days: 30
